# Generated by Django 2.2.5 on 2019-10-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20191013_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectratings',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aspectratings',
            name='hue',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aspectratings',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
