# Generated by Django 2.2.5 on 2019-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_auto_20191013_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectratings',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
