# Generated by Django 2.2.5 on 2019-10-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_auto_20191017_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectratings',
            name='rating',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
